# Generated by Django 4.2 on 2023-09-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalles', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol_local', models.IntegerField(default=0)),
                ('gol_visitante', models.IntegerField(default=0)),
                ('detalle', models.TextField()),
                ('horario_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos_horarios.horario')),
            ],
        ),
    ]
