# Generated by Django 4.2 on 2023-10-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos_horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('goles_a_favor', models.IntegerField(default=0)),
                ('goles_en_contra', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.ManyToManyField(to='partidos_horarios.partido')),
                ('tablas_partidos', models.ManyToManyField(to='tabla_posiciones.tablaposiciones')),
            ],
        ),
    ]
