# Generated by Django 4.2 on 2023-09-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('numero_ficha', models.IntegerField(blank=True, default=0, null=True)),
                ('jugador_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo_jugador.equipo')),
            ],
        ),
    ]
