# Generated by Django 4.2 on 2023-09-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_torneo_usuario_alter_torneo_fecha_final_and_more'),
        ('equipo_jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador_torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo_jugador.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.torneo')),
            ],
        ),
    ]
