# Generated by Django 4.2 on 2023-10-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_torneo_usuario_alter_torneo_fecha_final_and_more'),
        ('equipo_jugador', '0002_jugador_torneo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jugador_torneo',
            new_name='Equipo_torneo',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipo_jugador/media/equipo'),
        ),
    ]
